import type { Skill } from '@/types';

export const KnightSkills: Skill[] = [
  {
    id: 'Knight-Intimidate',
    name: 'Intimidate',
    description:
      'Knight presence strikes fear into enemies hearts slowing them down.',
    url: '',
    baseDamage: 0,
    damage: 0,
    duration: 0.7,
    speed: 1,
    action: 'idle',
    level: 1,
    cost: -1,
    multiplier: 1,
  },
  {
    id: 'Knight-PowerfulStab',
    name: 'Powerful Stab',
    description: 'A powerful attack thant penetrates light armour.',
    url: '',
    baseDamage: 80,
    damage: 80,
    duration: 0.4,
    speed: 1,
    action: 'attack',
    level: 1,
    cost: 15,
    multiplier: 1,
  },
  {
    id: 'Knight-GuardAlly',
    name: 'Guard Allies',
    description:
      'Knight shields his allies with large shield, increasing their defensive abilities.',
    url: '',
    baseDamage: 0,
    damage: 0,
    duration: 0.5,
    speed: 1,
    action: 'guard',
    level: 1,
    cost: 1,
    multiplier: 1,
    armor: 15,
  },
  {
    id: 'Knight-Defend',
    name: 'Defend',
    description: 'Knight stands still blocking most damage from enemy attacks',
    url: '',
    baseDamage: 0,
    damage: 0,
    duration: 0.1,
    speed: 1,
    action: 'protect',
    level: 1,
    cost: 2,
    multiplier: 1,
    armor: 50,
  },
];
