import type { Skill } from '@/types';

export const lightningMageSkills: Skill[] = [
  {
    id: 'LightningMage-Zap',
    name: 'Zap',
    description:
      'Generates Static field of electricity periodically zapping all enemies',
    url: '',
    baseDamage: 20,
    damage: 20,
    duration: 0.7,
    speed: 1,
    action: 'idle',
    level: 1,
    cost: 1,
    multiplier: 1,
  },
  {
    id: 'LightningMage-LightningStrike',
    name: 'Lightning Strike',
    description:
      'Lightning mages can summon lighting from the blue skies strikes all enemies neraby.',
    url: '',
    baseDamage: 110,
    damage: 110,
    duration: 1,
    speed: 1,
    action: 'attack',
    level: 1,
    cost: 10,
    multiplier: 1,
  },
  {
    id: 'LightningMage-ChargedBolts',
    name: 'Charged Bolts',
    description: 'Shoot small moving particles of electricity.',
    url: '',
    baseDamage: 60,
    damage: 60,
    duration: 0.4,
    speed: 1,
    action: 'chargedBolts',
    level: 1,
    cost: 1,
    multiplier: 15,
  },
  {
    id: 'LightningMage-LightningStream',
    name: 'Discharge',
    description: 'Release continous stream of electricity to closeby enemies.',
    url: '',
    baseDamage: 40,
    damage: 40,
    duration: 1.3,
    speed: 1,
    action: 'discharge',
    level: 1,
    cost: 25,
    multiplier: 1,
  },
];
