import type { Skill } from '@/types';

export const lightningMageSkills: Skill[] = [
  {
    id: 'LightningMage-Zap',
    name: 'Zap',
    description:
      'Generates a static field of electricity periodically, electrifying all enemies.',

    url: '',
    baseDamage: 5,
    damage: 5,
    duration: 0.7,
    speed: 1,
    action: 'idle',
    level: 1,
    cost: -1,
    multiplier: 1,
  },
  {
    id: 'LightningMage-LightningStrike',
    name: 'Lightning Strike',
    description:
      'Lightnig mage attaks summon lightning strikes to random areas on the field.',
    url: '',
    baseDamage: 150,
    damage: 150,
    duration: 1,
    speed: 1,
    action: 'attack',
    level: 1,
    cost: 15,
    multiplier: 1,
  },
  {
    id: 'LightningMage-ChargedBolts',
    name: 'Charged Bolts',
    description: 'Shoot small moving particles of electricity.',
    url: '',
    baseDamage: 30,
    damage: 30,
    duration: 0.4,
    speed: 1,
    action: 'chargedBolts',
    level: 1,
    cost: 10,
    multiplier: 1,
  },
  {
    id: 'LightningMage-LightningStream',
    name: 'Discharge',
    description: 'Release continous stream of electricity to closeby enemies.',
    url: '',
    baseDamage: 40,
    damage: 40,
    duration: 1.3,
    speed: 1,
    action: 'discharge',
    level: 1,
    cost: 25,
    multiplier: 1,
  },
];
