/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface GameScore {
  date: string;
  id: Generated<number>;
  name: string;
  score: number;
}

export interface GameUser {
  date: string;
  email: string;
  id: Generated<number>;
  name: string;
  password: string;
}

export interface DB {
  "game.score": GameScore;
  "game.user": GameUser;
}
